# Generated by Django 5.2.14 on 2026-05-14 04:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_number', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('called', 'Called'), ('serving', 'Serving'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='waiting', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('estimated_time', models.DateTimeField(blank=True, null=True)),
                ('called_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_emergency', models.BooleanField(default=False)),
                ('emergency_reason', models.TextField(blank=True)),
                ('emergency_document', models.FileField(blank=True, null=True, upload_to='emergency_docs/')),
                ('emergency_approved', models.BooleanField(default=False)),
                ('booking_date', models.DateField()),
                ('archived', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='organizations.organization')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='organizations.service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='QueueHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='queue.token')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddConstraint(
            model_name='token',
            constraint=models.UniqueConstraint(fields=('service', 'token_number', 'booking_date'), name='uniq_token_number_per_service_day'),
        ),
    ]
