# Generated by Django 5.2.14 on 2026-05-14 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_is_organizer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_organizer',
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('user', 'Public User'), ('organizer', 'Organizer')], default='user', max_length=20),
        ),
    ]
