# Generated by Django 5.2.14 on 2026-05-14 05:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_seed_demo_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='organizers',
            field=models.ManyToManyField(blank=True, related_name='managed_organizations', to=settings.AUTH_USER_MODEL),
        ),
    ]
